version: '3.5'

services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.0

  webserver:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./airflow.env
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/logs:/usr/local/airflow/logs
      - ./data/webserver:/usr/local/airflow_data
    ports:
      - 8080:8080
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: wizart/docker-airflow:latest
    build:
      context: .
    restart: always
    depends_on:
      - webserver
    env_file:
      - ./airflow.env
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/logs:/usr/local/airflow/logs
      - ./data/webserver:/usr/local/airflow_data
    command: scheduler

  worker:
    image: wizart/docker-airflow:latest
    build:
      context: .
    restart: always
    depends_on:
      - scheduler
    env_file:
      - ./airflow.env
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/logs:/usr/local/airflow/logs
      - ./data/webserver:/usr/local/airflow_data
    command: worker

  flower:
    image: wizart/docker-airflow:latest
    build:
      context: .
    restart: always
    depends_on:
      - redis
    env_file:
      - ./airflow.env
    ports:
      - 5555:5555
    command: flower